apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pgi-les-inntekt-skatt
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  image: {{ image }}
  port: 8080
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "skatteetaten:pensjonsgivendeinntektforfolketrygden"
  kafka:
    pool: nav-dev
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 50
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 50
  prometheus:
    enabled: true
    path: /actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  secureLogs:
    enabled: true
  replicas:
    min: 1
    max: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: APP_TEAM
      value: pensjonopptjening
    - name: SKATT_INNTEKT_HOST
      value: https://pgiforfolketrygden.api.skatteetaten-test.no
    - name: SKATT_INNTEKT_PATH
      value: /v1/navPensjonOpptjening
  accessPolicy:
    outbound:
      external:
        - host: pgiforfolketrygden.api.skatteetaten-test.no
