apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pgi-les-inntekt-skatt
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  image: {{ image }}
  team: pensjonopptjening
  port: 8080
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "skatteetaten:pensjonsgivendeinntektforfolketrygden"
  envFrom:
    - secret: pgi-les-inntekt-skatt-secrets
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  liveness:
    path: isAlive
    initialDelay: 30
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: isReady
    initialDelay: 30
    periodSeconds: 1
    failureThreshold: 60
  secureLogs:
    enabled: true
  replicas:
    min: 1
    max: 1
  env:
    - name: APP_TEAM
      value: pensjonopptjening
  accessPolicy:
    outbound:
      external:
        - host: api.skatteetaten.no
