apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pgi-les-inntekt-skatt
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  image: {{ image }}
  port: 8080
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "skatteetaten:pensjonsgivendeinntektforfolketrygden"
  kafka:
    pool: nav-dev
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 50
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 50
  prometheus:
    enabled: true
    path: /actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  replicas:
    min: 1
    max: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: APP_TEAM
      value: pensjonopptjening
    - name: SKATT_INNTEKT_HOST
      value: https://pgiforfolketrygden.api.skatteetaten-test.no
    - name: SKATT_INNTEKT_PATH
      value: /v1/navPensjonOpptjening
    - name: JAVA_TRUSTSTORE_OPTIONS
      value: "-Djavax.net.ssl.trustStore=$(NAV_TRUSTSTORE_PATH)
              -Djavax.net.ssl.trustStorePassword=$(NAV_TRUSTSTORE_PASSWORD)"
    - name: JDK_JAVA_OPTIONS
      value: "-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/ -Xmx256m -Djdk.tls.client.protocols=TLSv1.2 $(JAVA_TRUSTSTORE_OPTIONS)"
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - host: pgiforfolketrygden.api.skatteetaten-test.no
