apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pgi-les-inntekt-skatt
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  image: {{ image }}
  port: 8080
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "skatteetaten:pensjonsgivendeinntektforfolketrygden"
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  liveness:
    path: isAlive
    initialDelay: 30
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: isReady
    initialDelay: 30
    periodSeconds: 1
    failureThreshold: 60
  secureLogs:
    enabled: true
  replicas:
    min: 1
    max: 1
  env:
    - name: APP_TEAM
      value: pensjonopptjening
    - name: SKATT_INNTEKT_HOST
      value: https://api.skatteetaten.no
    - name: SKATT_INNTEKT_PATH
      value: /api/formueinntekt/pensjonsgivendeinntektforfolketrygden
  accessPolicy:
    outbound:
      external:
        - host: api.skatteetaten.no
