apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pgi-les-inntekt-skatt
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  team: pensjonsamhandling
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  liveness:
    path: isAlive
    initialDelay: 30
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: isReady
    initialDelay: 30
    periodSeconds: 1
    failureThreshold: 60
  replicas:
    min: 1
    max: 1
  env:
    - name: APP_TEAM
      value: pensjonsamhandling