name: Deploy to dev gcp

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  deploy-to-dev:
    name: 'Bygg og deploy test'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5

      - name: 'Java 21'
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          java-package: jdk

      - name: 'Setup Gradle'
        uses: gradle/actions/setup-gradle@v5

      - name: 'Generate and submit dependency graph'
        uses: gradle/actions/dependency-submission@v5

      - name: 'Setter dato og commit variabel'
        run: |
          export TZ=CET
          echo "DATE=$(date '+%Y-%m-%d--%H-%M-%S')" >> $GITHUB_ENV
          echo "GIT_COMMIT=$(echo ${{github.sha}} | cut -c 1-7)" >> $GITHUB_ENV
          echo "GIT_BRANCH=$(echo ${{github.ref_name}})" >> $GITHUB_ENV

      - name: 'Configure git reference tag'
        run: |
          echo "GIT_REF_TAG=git_${GIT_BRANCH}_${GIT_COMMIT}" >> $GITHUB_ENV

      - name: 'Build artifact'
        run: |
          ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push docker image'
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: pensjonopptjening
          tag: ${{ env.GIT_REF_TAG }}

      - name: 'Deploy pgi-les-inntekt-skatt (dev-gcp)'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais-gcp-dev.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}
          TELEMETRY: ${{ steps.docker-push.outputs.telemetry }}