name: 'Monitor dependencies with Dependabot'
on:
  schedule:
    - cron: '25 8,13 * * 1,2,3,4,5'
    - cron: '25 13 * * 0,6'
jobs:
  dependabot:
    name: Monitor dependencies with Dependabot
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: 'Checkout repository'
        uses: actions/checkout@v5

      - name: 'Java 21'
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: 'Generate and submit dependency graph'
        uses: gradle/actions/dependency-submission@v5
